/* ============================================================
   contract_text.js — Contract labels + clauses in KU / AR / EN
   Clause functions receive (c, x):
     c        = the contract record
     x.m(n)   = formatted money amount (localized)
     x.office = office/company name (escaped; blank or generic if unset)
     x.court  = court name (escaped; city from Settings or generic)
   Interpolated user values are escaped with esc(); static text is trusted.
   ============================================================ */

const CONTRACT_TEXT = {
  labels: {
    ku: {
      date: "بەروار", contractNo: "ژمارەی گرێبەست",
      saleTitle: "(گرێبەستی کڕین و فرۆشتن)", rentTitle: "(گرێبەستی بەکرێدان)",
      banner: "هەردوو لایەن لەسەر ئەم مەرجانە ڕێککەوتن", note: "تێبینی",
      p_first: "لایەنی یەکەم", p_second: "لایەنی دووەم", p_location: "شوێن",
      p_type: "جۆری موڵک", p_number: "ژمارەی موڵک", p_area: "ڕووبەر",
      s_seller: "لایەنی یەکەم (فرۆشیار)", s_buyer: "لایەنی دووەم (کڕیار)",
      s_owner: "لایەنی یەکەم (خاوەن موڵک)", s_tenant: "لایەنی دووەم (کرێچی)",
      s_organizer: "ڕێکخەری گرێبەست",
    },
    ar: {
      date: "التاريخ", contractNo: "رقم العقد",
      saleTitle: "(عقد بيع وشراء)", rentTitle: "(عقد إيجار)",
      banner: "اتفق الطرفان على هذه الشروط", note: "ملاحظة",
      p_first: "الطرف الأول", p_second: "الطرف الثاني", p_location: "الموقع",
      p_type: "نوع العقار", p_number: "رقم العقار", p_area: "المساحة",
      s_seller: "الطرف الأول (البائع)", s_buyer: "الطرف الثاني (المشتري)",
      s_owner: "الطرف الأول (المالك)", s_tenant: "الطرف الثاني (المستأجر)",
      s_organizer: "منظّم العقد",
    },
    en: {
      date: "DATE", contractNo: "CONTRACT NUMBER",
      saleTitle: "(BUY AND SALE CONTRACT)", rentTitle: "(RENT CONTRACT)",
      banner: "Both parties agreed on these terms", note: "Note",
      p_first: "First Party", p_second: "Second Party", p_location: "Location",
      p_type: "Property", p_number: "Number", p_area: "Area",
      s_seller: "First Party (Seller)", s_buyer: "Second Party (Buyer)",
      s_owner: "First side (property owner)", s_tenant: "Second side (tenant)",
      s_organizer: "Contract Organizer",
    },
  },

  // Fallbacks when the office name / court city aren't set in Settings.
  generic: {
    office: { ku: "ئۆفیسی خانووبەرە", ar: "المكتب العقاري", en: "the Real Estate Office" },
    court: { ku: "دادگای پەیوەندیدار", ar: "المحكمة المختصة", en: "the competent" },
  },

  sale: {
    ku: (c, x) => [
      `من لایەنی یەکەم (${esc(c.firstParty || "")}) خاوەنی موڵکەکە، ڕازیبووم بە فرۆشتنی ئەو موڵکەی سەرەوە بە بڕی ${x.m(c.price)}.`,
      `من لایەنی دووەم (${esc(c.secondParty || "")}) ڕازیبووم بە کڕینی ئەو موڵکەی سەرەوە بە بڕی ${x.m(c.price)}.`,
      `لایەنی دووەم بڕی ${x.m(c.moneyAdvance)} دەداتە لایەنی یەکەم وەک پێشەکی، و بڕی ماوە (${x.m(c.moneyLeft)}) دەبێت لە بەرواری (${esc(c.paymentDateLeft || "")}) بدرێت بە نەقد یان بە قیست.`,
      `لایەنی یەکەم موڵکەکە ڕادەستی لایەنی دووەم دەکات دوای وەرگرتنی هەموو مافە داراییەکانی لە بەرواری ${esc(c.dateSurrender || "")}.`,
      `ئەگەر لایەنی یەکەم دواکەوت لە ڕادەستکردنی موڵکەکە بۆ لایەنی دووەم، دەبێت بڕی ${x.m(c.punishment)} بدات وەک سزا بۆ هەر ڕۆژێکی دواکەوتن.`,
      `لایەنی یەکەم پابەندە بە دانەوەی تێچووی ئاو و کارەبا یان هەر قەرزێکی تر پێش بەرواری ڕادەستکردنی موڵکەکەی سەرەوە.`,
      `ئەگەر هەر لایەنێک بۆ هەر هۆکارێک پاشگەز بووەوە، دەبێت بڕی ${x.m(c.amountDissuade)} وەک سزا بدات.`,
      `تێچوو و کرێی فرۆشتن و گواستنەوە و جیاکردنەوە و یەکخستن و گۆڕانکاری و باجی موڵک لەسەر لایەنی یەکەمە بەپێی یاسا ئەگەر موڵکەکە تاپۆی هەبێت. ئەگەر تاپۆی نەبێت، لایەنی یەکەم تێچووی گواستنەوەی خاوەندارێتی دەدات.`,
      `لایەنی دووەم بەرپرسە لە دانی کرێی پشکنین و تۆمارکردنی موڵک بەپێی یاسا ئەگەر موڵکەکە تاپۆی هەبێت، و ئەگەر تاپۆی نەبێت هەردوو لایەن تێچووی تۆمارکردن دەدەن.`,
      `دوای واژووکردنی ئەم گرێبەستە و ئەگەر موڵکە فرۆشراوەکە تاپۆی هەبێت، لایەنی یەکەم وەکالەت دەداتە پارێزەر (${esc(c.lawyerName || "")}) بۆ مەبەستی گواستنەوەی خاوەندارێتی و تۆمارکردنی موڵکە فرۆشراوەکە بۆ سوودی لایەنی دووەم.`,
      `لایەنی یەکەم و لایەنی دووەم پابەندن بە دانی ١٪ لە نرخی موڵکەکەی ناو ئەم گرێبەستە بۆ ${x.office} لە بەرامبەر فرۆشتنی موڵکەکە.`,
      `ئەگەر هەر ناکۆکییەک لەسەر ناوەرۆکی ئەم گرێبەستە دروستبوو، هەردوو لایەن بە گفتوگۆ چارەسەری دەکەن، ئەگەرنا دادگای ${x.court} شوێنی بڕیاردانە لەسەر کێشەکان.`,
      `لایەنی یەکەم و لایەنی دووەم دوای واژووکردنی گرێبەست بۆیان نییە داوای ئەو کۆمیشنە بکەن کە دراوە بە ${x.office}.`,
      `کاری ئۆفیس تەنها ناوبژیوانییە، و بەرپرس نییە لە هیچ کێشە یان ناکۆکییەک کە لەنێوان فرۆشیار و کڕیاردا ڕوودەدات.`,
    ],
    ar: (c, x) => [
      `أنا الطرف الأول (${esc(c.firstParty || "")}) مالك العقار، وافقت على بيع العقار المذكور أعلاه بمبلغ قدره ${x.m(c.price)}.`,
      `أنا الطرف الثاني (${esc(c.secondParty || "")}) وافقت على شراء العقار المذكور أعلاه بمبلغ قدره ${x.m(c.price)}.`,
      `يدفع الطرف الثاني مبلغاً قدره ${x.m(c.moneyAdvance)} إلى الطرف الأول كعربون (مقدَّم)، والمبلغ المتبقي (${x.m(c.moneyLeft)}) يجب دفعه بتاريخ (${esc(c.paymentDateLeft || "")}) نقداً أو بالتقسيط.`,
      `يسلّم الطرف الأول العقار إلى الطرف الثاني بعد استلام كامل مستحقاته المالية بتاريخ ${esc(c.dateSurrender || "")}.`,
      `في حال تأخر الطرف الأول عن تسليم العقار إلى الطرف الثاني، يدفع مبلغاً قدره ${x.m(c.punishment)} كغرامة عن كل يوم تأخير.`,
      `يلتزم الطرف الأول بتسديد أجور وفواتير الماء والكهرباء أو أي دين آخر قبل تاريخ تسليم العقار المذكور أعلاه.`,
      `في حال عدول أحد الطرفين لأي سبب، عليه دفع غرامة قدرها ${x.m(c.amountDissuade)}.`,
      `تكون تكاليف وأجور البيع والنقل والفرز والتوحيد والتعديل وضريبة العقار على عاتق الطرف الأول وفقاً للقانون إذا كان للعقار سند ملكية (طابو). وفي حال عدم وجود سند ملكية، يتحمل الطرف الأول تكاليف نقل الملكية.`,
      `يتحمل الطرف الثاني أجور الكشف والتسجيل العقاري وفقاً للقانون إذا كان للعقار سند ملكية، وإذا لم يكن للعقار سند ملكية فيتحمل الطرفان تكاليف التسجيل.`,
      `بعد توقيع هذا العقد وفي حال وجود سند ملكية للعقار المباع، يمنح الطرف الأول وكالة للمحامي (${esc(c.lawyerName || "")}) لغرض نقل الملكية وتسجيل العقار المباع لصالح الطرف الثاني.`,
      `يتعهد الطرف الأول والطرف الثاني بدفع ١٪ من ثمن العقار المذكور في هذا العقد إلى ${x.office} مقابل بيع العقار.`,
      `في حال نشوء أي خلاف حول مضمون هذا العقد، يحلّه الطرفان بالحوار، وإلا تكون محكمة ${x.court} هي الجهة المختصة بالبت في القضايا.`,
      `لا يحق للطرف الأول والطرف الثاني بعد توقيع العقد المطالبة بالعمولة المدفوعة إلى ${x.office}.`,
      `عمل المكتب هو الوساطة فقط، وهو غير مسؤول عن أي مشكلة أو نزاع يقع بين البائع والمشتري.`,
    ],
    en: (c, x) => [
      `I am the first side (${esc(c.firstParty || "")}) the owner of the property agreed to sell the above mentioned property for an amount of ${x.m(c.price)}.`,
      `I am the second side (${esc(c.secondParty || "")}) accepted to purchase the above mentioned property for an amount of ${x.m(c.price)}.`,
      `The Second side shall pay an amount of ${x.m(c.moneyAdvance)} to the first side as an advance, and The remaining amount (${x.m(c.moneyLeft)}) must be pay on the date (${esc(c.paymentDateLeft || "")}) pay in (cash or installment).`,
      `The first side shall hand over the property to the second side after receiving all its financial dues on date ${esc(c.dateSurrender || "")}.`,
      `In the event that the first side is late in handing over the property to the second side, it must pay an amount of ${x.m(c.punishment)} as a fine for each day of delay.`,
      `The first side shall liquidate the costs and fees of water and electricity or any other loan before the date of handing over the above mention property.`,
      `For any reason for the retraction of one of the two sides, he must pay a penalty of amount ${x.m(c.amountDissuade)}.`,
      `The costs and fees of sale, transportation, sorting, consolidation, modification, and real estate tax are borne by the first side in accordance with the law if the property has a title deed. In the event that the property does not have a title deed, the first side must pay the costs of transferring ownership.`,
      `The second side is responsible for paying the inspection and real estate registration fees according to the law if the property has a title deed, and if the property does not have a title deed, the both side must pay the registration costs.`,
      `After signing this contract in the event that the sold property has a title deed, the first side must grant an agency to attorney (${esc(c.lawyerName || "")}) for the purpose of transferring ownership and registering the sold property for the benefit of the second party.`,
      `The first side and the second side undertakes to pay 1% of the price of the property mentioned in this contract to the ${x.office} for the sale of the property.`,
      `In the event of any dispute about the content of this contract, the two parties must resolve it through dialogue, otherwise the ${x.court} court will be the place to decide the cases.`,
      `The first side and the second side, after signing the contract, are not entitled to claim the commission given to the ${x.office}.`,
      `The company's job is only mediation. It is not responsible for any problem or dispute that occurs between the seller and the buyer.`,
    ],
  },

  rent: {
    ku: (c, x) => [
      `لایەنی یەکەم ڕازیدەبێت بە بەکرێدانی ئەو موڵکەی سەرەوە بە لایەنی دووەم.`,
      `ماوەی گرێبەست (${esc(c.rentalPeriod || "")}) مانگە، دەستپێدەکات لە (${esc(c.dateOf || "")}) تا (${esc(c.forDate || "")})، و دوای کۆتایی گرێبەست دەبێت لایەنی دووەم موڵکەکە چۆڵ بکات بەبێ ئاگادارکردنەوەی پێشوەخت.`,
      `هەردوو لایەن ڕێککەوتن لەسەر ئەوەی بڕی کرێ ${x.m(c.amount)} بێت.`,
      `لایەنی دووەم بڕی ${x.m(c.moneyAdvance)} دەدات وەک پێشەکی بۆ (${esc(c.monthlyAdvance || "")}) مانگ.`,
      `لایەنی دووەم پابەندە بە دانی بڕی ${x.m(c.assurances)} وەک دەستەبەر (تأمین) بۆ ${x.office} بەپێی وەسڵێکی ژمارەدار، و بڕەکە بە هەمان وەسڵ دەگەڕێتەوە بۆ لایەنی دووەم دوای کۆتایی ماوەی گرێبەست، بەمەرجێک موڵکەکە بەبێ هیچ کەموکوڕییەک ڕادەستی لایەنی یەکەم بکرێتەوە.`,
      `لایەنی دووەم ئەم موڵکە بۆ مەبەستی (${esc(c.forPurposes || "")}) بەکاردەهێنێت، و لە کاتی بەکارهێنانی بۆ هەر مەبەستێکی تر دەبێت ${x.office} ئاگادار بکاتەوە بە ڕەزامەندی نووسراوی لایەنی یەکەم، ئەگەرنا لایەنی یەکەم مافی هەیە گرێبەستەکە هەڵبوەشێنێتەوە بەبێ ئاگادارکردنەوەی لایەنی دووەم.`,
      `لایەنی دووەم پابەندە بە پاراستنی موڵکە بەکرێدراوەکە لە تێکچوون و ڕووخان و بەکارنەهێنانی بە شێوەیەکی نەخوازراو.`,
      `لە بەرواری واژووکردنی گرێبەستەوە، لایەنی دووەم بەرپرسە لە دانی تێچووی ئاو و کارەبا و بەلەدیە و هەر خزمەتگوزارییەکی تر.`,
      `لایەنی دووەم پابەندە بە دانی کرێ لە کاتی دیاریکراوی گرێبەستدا، و ئەگەر زیاتر لە (٧) ڕۆژ دواکەوت، بەپێی بڕگەی (١) لە ماددەی (١٧)ی یاسای بەکرێدانی موڵکی عێراقی ژمارە (٨٧)ی ساڵی (١٩٧٩) هەڵسوکەوتی لەگەڵ دەکرێت، کە بریتییە لە چۆڵکردنی موڵکەکە لەگەڵ دانی تێچووی ئاگادارکردنەوەی دادگا لەگەڵ کرێی مانگانە.`,
      `ئەگەر موڵکە بەکرێدراوەکە کەلوپەلی تێدابێت، دەبێت لایەنی دووەم کەلوپەلەکە بپارێزێت و لە کاتی چۆڵکردندا وەک خۆی ڕادەستی بکاتەوە، ئەگەرنا لایەنی دووەم بەرپرسە لە چاککردنەوە یان گۆڕینەوەی بە خەرجی خۆی.`,
      `دوای کۆتایی ماوەی گرێبەست، ئەگەر لایەنی دووەم پابەند نەبوو بە چۆڵکردنی موڵکەکە یان نوێکردنەوەی گرێبەست، کرێی موڵکەکە دەبێت ${x.m(c.punishPerDay)} بۆ هەر ڕۆژێک تا کێشەکە چارەسەر دەبێت.`,
      `ئەگەر خاوەندارێتی موڵکەکە بۆ لایەنێکی تر گوازرایەوە، دەبێت خاوەنە نوێیەکە پابەند بێت بە ناوەرۆکی ئەم گرێبەستە.`,
      `هەردوو لایەن دەبێت نیوەی بڕی کرێ ساڵانە بدەن بە ${x.office} لە بەرامبەر ڕێکخستنی ئەم گرێبەستە.`,
      `لە کاتی چۆڵکردنی موڵکەکە، دەبێت لایەنی دووەم موڵکەکە وەک ئەوەی وەریگرتووە ڕادەستی بکاتەوە بەبێ هیچ کەموکوڕییەک، ئەگەرنا بەرپرسە لە پڕکردنەوەی کەموکوڕییەکان لە زووترین کاتدا.`,
      `لە کاتی نوێکردنەوەی گرێبەست، هەردوو لایەن پابەندن بە دانی نیوەی بڕی کرێ ساڵانە بۆ ${x.office}.`,
      `بۆ لایەنی دووەم نییە بە هیچ شێوەیەک کێشە لەگەڵ دراوسێکان دروست بکات، ئەگەرنا بەرپرسیارێتی دەگرێتە ئەستۆ و گرێبەستەکە هەڵدەوەشێتەوە.`,
      `کاتێک کێشەکان بە گفتوگۆ لەنێوان هەردوو لایەندا چارەسەر نەبوون، ${x.office} بەرپرس نییە، بەڵکو دەبێت هەردوو لایەن کێشەکان بە ڕێکارە یاساییەکان چارەسەر بکەن و پەنا بۆ دادگای ${x.court} ببەن.`,
      `${x.office} بەرپرس نییە لە هیچ کێشەیەک کە لەنێوان هەردوو لایەندا ڕوودەدات.`,
    ],
    ar: (c, x) => [
      `يوافق الطرف الأول على تأجير العقار المذكور أعلاه إلى الطرف الثاني.`,
      `مدة العقد (${esc(c.rentalPeriod || "")}) شهراً، تبدأ من (${esc(c.dateOf || "")}) وحتى (${esc(c.forDate || "")})، وبعد انتهاء العقد يجب على الطرف الثاني إخلاء العقار دون إشعار مسبق.`,
      `اتفق الطرفان على أن يكون مبلغ الإيجار ${x.m(c.amount)}.`,
      `يدفع الطرف الثاني مبلغاً قدره ${x.m(c.moneyAdvance)} كمقدَّم عن (${esc(c.monthlyAdvance || "")}) أشهر.`,
      `يلتزم الطرف الثاني بدفع مبلغ قدره ${x.m(c.assurances)} كتأمين إلى ${x.office} بموجب وصل مرقّم، ويُعاد المبلغ بنفس الوصل إلى الطرف الثاني بعد انتهاء مدة العقد، شريطة تسليم العقار دون أي نقص من الطرف الثاني إلى الطرف الأول.`,
      `يستعمل الطرف الثاني هذا العقار لغرض (${esc(c.forPurposes || "")})، وعند استعماله لأي غرض آخر يجب إعلام ${x.office} بموافقة خطية من الطرف الأول، وإلا يحق للطرف الأول فسخ العقد دون إعلام الطرف الثاني.`,
      `يتعهد الطرف الثاني بالمحافظة على العقار المؤجَّر وصيانته من التلف والهدم وعدم استعماله بطريقة غير مرغوبة.`,
      `من تاريخ توقيع العقد يكون الطرف الثاني مسؤولاً عن دفع أجور الماء والكهرباء والبلدية وأي خدمة أخرى.`,
      `يتعهد الطرف الثاني بدفع الإيجار في الموعد المحدد في العقد، وإذا تأخر أكثر من (٧) أيام يُعامَل وفق الفقرة (١) من المادة (١٧) من قانون إيجار العقار العراقي رقم (٨٧) لسنة (١٩٧٩)، وهو إخلاء العقار مع تحمّل أجور إشعار المحكمة إضافة إلى الإيجار الشهري.`,
      `إذا كان العقار المؤجَّر مفروشاً، يجب على الطرف الثاني المحافظة على الأثاث وتسليمه كما كان عند الإخلاء، وإلا يكون الطرف الثاني مسؤولاً عن إصلاحه أو استبداله على نفقته.`,
      `بعد انتهاء مدة العقد، في حال عدم التزام الطرف الثاني بإخلاء العقار أو تجديد العقد، يكون إيجار العقار ${x.m(c.punishPerDay)} عن كل يوم إلى أن تُحلّ القضية.`,
      `إذا انتقلت ملكية العقار إلى طرف آخر، يجب على المالك الجديد الالتزام بمضمون هذا العقد.`,
      `يجب على الطرفين دفع نصف مبلغ الإيجار سنوياً إلى ${x.office} مقابل تنظيم هذا العقد.`,
      `عند إخلاء العقار، يجب على الطرف الثاني تسليم العقار كما استلمه دون أي نقص، وإلا يتحمل مسؤولية سدّ النواقص في أقرب وقت.`,
      `عند تجديد العقد، يتعهد الطرفان بدفع نصف مبلغ الإيجار سنوياً إلى ${x.office}.`,
      `لا يحق للطرف الثاني بأي شكل إثارة المشاكل مع الجيران، وإلا يتحمل المسؤولية ويُفسخ العقد.`,
      `عند عدم حل المشاكل بالحوار بين الطرفين، لا يتحمل ${x.office} المسؤولية، بل يجب على الطرفين حل القضايا بالإجراءات القانونية واللجوء إلى محكمة ${x.court}.`,
      `${x.office} غير مسؤول عن أي مشاكل تقع بين الطرفين.`,
    ],
    en: (c, x) => [
      `The first side accepts to rent the above mentioned property to the second side.`,
      `The contract period is (${esc(c.rentalPeriod || "")})months, start from (${esc(c.dateOf || "")}) till (${esc(c.forDate || "")}) , and After the end of the contract, the second party must vacate the property without prior notification.`,
      `both side agreed to the rent amount on an amount of ${x.m(c.amount)}`,
      `The second side pays an amount of ${x.m(c.moneyAdvance)}. as an advance of (${esc(c.monthlyAdvance || "")}) months.`,
      `The second side is obligated to pay an amount of ${x.m(c.assurances)}.as insurance to the ${x.office} according to the numbered receipt paper, and the amount is delivered on the same receipt paper to the second side after the end of the contract period, provided that the property is delivered without any deficiency by the second side to the first side.`,
      `The second side uses this property for a (${esc(c.forPurposes || "")}) purpose, and when using it for any other purpose, should be inform the ${x.office} with the written consent of the first side. Otherwise, the first side has the right to void the contract without informing the second side.`,
      `The second side undertakes to protect the leased property from benefiting from it and to preserve it from damage and demolition and not to use it in an unwanted manner.`,
      `From the date of signing the contract, the second side is responsible for paying the costs of water, electricity, the municipality and any other service.`,
      `The second side undertakes to pay the rent at the time specified in the contract. If he is more than (7) days late, he will deal with him according to Paragraph (1) of Article (17) of the Real Estate Rental Law of Iraqi Law No. (87) for the year (1979), which is vacating the property while bearing the costs of notifying the court along with the monthly rent.`,
      `If the leased property is furnished, the second party must preserve the furniture and, when vacating it, hand it over as it was; Otherwise, the second side shall be responsible for repairing or replacing it at its own risk.`,
      `After the end of the contract period, in the event that the second side does not abide by vacating the property or renewing the contract, the property rent will be ${x.m(c.punishPerDay)}per day until the case is resolved.`,
      `If ownership of the property is transferred to another side, the new owner must abide by the content of this contract.`,
      `The two sides must pay half of the amount of the rent annually to ${x.office} instead of organizing this contract.`,
      `Upon vacating the property, the second side must hand over the property as it received it without any defects. Otherwise, it bears the responsibility to fill the deficiencies as soon as possible.`,
      `Upon renewal of the contract, the two parties undertake to pay half the amount of the rent annually to the ${x.office}.`,
      `The second side is not entitled in any way or creates problems with neighbors, otherwise he bears responsibility and the contract is terminated.`,
      `When the problems are not resolved through dialogue between the two parties, the ${x.office} does not bear the responsibility, but the two sides must resolve the issues through legal procedures and resort to a ${x.court} court.`,
      `${x.office} is not responsible for any problems that occur between the two sides.`,
    ],
  },
};
